package com.bsoft.common.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarryXmlToDbService", targetNamespace = "http://webservice.entrance.si.neusoft.com/")
public interface CarryXmlToDbService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handleFile", targetNamespace = "http://webservice.entrance.si.neusoft.com/", className = "com.neusoft.si.entrance.webservice.HandleFile")
    @ResponseWrapper(localName = "handleFileResponse", targetNamespace = "http://webservice.entrance.si.neusoft.com/", className = "com.neusoft.si.entrance.webservice.HandleFileResponse")
    public String handleFile(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handleHistory", targetNamespace = "http://webservice.entrance.si.neusoft.com/", className = "com.neusoft.si.entrance.webservice.HandleHistory")
    @ResponseWrapper(localName = "handleHistoryResponse", targetNamespace = "http://webservice.entrance.si.neusoft.com/", className = "com.neusoft.si.entrance.webservice.HandleHistoryResponse")
    public String handleHistory(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0)
        throws Exception
    ;

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handle", targetNamespace = "http://webservice.entrance.si.neusoft.com/", className = "com.neusoft.si.entrance.webservice.Handle")
    @ResponseWrapper(localName = "handleResponse", targetNamespace = "http://webservice.entrance.si.neusoft.com/", className = "com.neusoft.si.entrance.webservice.HandleResponse")
    public String handle(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0)
        throws Exception
    ;

}
